---
title: Proxy Race Estimation in North Carolina
date: January 11, 2022
output: distill::distill_article
---

```{r setup, include=F}
library(tidyverse)
suppressMessages(library(here))
devtools::load_all(here("."))
```

# Model

# Data

```{r prep}
if (!interactive()) {
    voterfile <- here("data/nc_voters.rds")
    voters = read_rds(voterfile) 
} else {
    voters = make_nc_df("Robeson") # try Duplin, Hoke, Robeson, Durham, Orange, Wake (largest)
}

# tables
p_xr = prop.table(table(voters$party, voters$race))[, c("white", "black", "hisp", "asian", "other")]
p_x = rowSums(p_xr)
p_r = colSums(p_xr)
```

# Fitting the model

```{r fit, message=F, warning=F}
fit = model_race(party, last_name, zip, data=voters, p_r=p_r,
                 regularize=F, alpha=10,
                 gibbs=T, stan=T, stan_method="vb", 
                 iter=300, verbose=TRUE)
xr = calc_joints(p_xr, voters, fit)
```

```{r confounding}
# evaluate confounding
I_dem = voters$party == "dem"
I_white = voters$race == "white"
pr_white = fit$baseline[, "white"]
summary(glm(I_dem ~ I_white + pr_white, family=binomial()))$coefficients %>%
     knitr::kable()
```

# Evaluating the methods

```{r peek}
print_cond(xr$true, "true")
print_cond(xr$base, "naive bayes")
print_cond(xr$stan, "stan")
```

```{r eval}
eval_joints(p_xr, "tv",
            naive_name = xr$base_surn,
            naive = xr$base,
            gibbs = xr$gibbs,
            gibbs_raked = rake(xr$gibbs, p_x, p_r),
            lsq = fit$lsq,
            lsq_raked = rake(fit$lsq, p_x, p_r),
            nnls = fit$nnls,
            nnls_raked = rake(fit$nnls, p_x, p_r),
            stan = xr$stan) %>%
     knitr::kable()
```


# Appendix

Checking marginal race probabilities:

```{r marginal}
# marginal race probabilities
warmup = 1:100
p_r
colMeans(fit$base_surn)
colMeans(fit$baseline)
prop.table(table(as.integer(fit$gibbs[, -warmup])))
```

Are the errors in $p(X, R)$ correlated between the methods?

```{r errors}
# where is the improvement coming from / are the errors correlated
cor(as.numeric(xr$gibbs - xr$true), as.numeric(xr$stan - xr$true))
cor(as.numeric(xr$gibbs - xr$base), as.numeric(xr$stan - xr$base))
cor(as.numeric(rake(fit$nnls, p_x, p_r) - xr$base), as.numeric(xr$stan - xr$base))
```
