test_that("Surnames are processed following Census rules", {
    expect_equal(proc_names("SMITH  "), "SMITH")
    expect_equal(proc_names(" García"), "GARCIA")
    expect_equal(proc_names("SMITH-JONES"), "SMITH JONES")
    expect_equal(proc_names("O HARA"), "OHARA")
    expect_equal(proc_names("O'HARA"), "OHARA")
    expect_equal(proc_names("MC CARTAN"), "MCCARTAN")
    expect_equal(proc_names("Mac DONALD"), "MACDONALD")
    expect_equal(proc_names("A A"), NA_character_)
    expect_equal(proc_names("C D"), NA_character_)
    expect_equal(proc_names("S M I T H"), "SMITH")
    expect_equal(proc_names("JONES JUNIOR"), "JONES")
    expect_equal(proc_names("JR SMITH III"), "SMITH")
    expect_equal(proc_names("NASR"), "NASR")
    expect_equal(proc_names("WILSONJR"), "WILSON")
    expect_equal(proc_names("WILSONSR"), "WILSON")
    expect_equal(proc_names("JONES II"), "JONES")
    expect_equal(proc_names("JONES IV"), "JONES")
    expect_equal(proc_names("NISHII"), "NISHII")
    expect_equal(proc_names("GONZALEZ S R"), "GONZALEZ")
    expect_equal(proc_names("AA"), "AA")
    expect_equal(proc_names("AB"), "AB")
    expect_equal(proc_names("BY"), "BY")
    expect_equal(proc_names("BC"), NA_character_)
    expect_equal(proc_names("DECLINE TO STATE"), NA_character_)
})

test_that("Double-barrelled names are detected", {
    expect_true(is_double_name("OCASIO CORTEZ"))
    expect_false(is_double_name("SMITH"))
})
