// Generated by rstantools.  Do not edit by hand.

/*
    race-proxy is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    race-proxy is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with race-proxy.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_simple_additive_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_simple_additive");
    reader.add_event(91, 89, "end", "model_simple_additive");
    return reader;
}
#include <stan_meta_header.hpp>
class model_simple_additive
  : public stan::model::model_base_crtp<model_simple_additive> {
private:
        int N;
        int n_x;
        int n_r;
        int n_gz;
        int n_gz_col;
        std::vector<int> X;
        matrix_d GZ;
        int n_nonzero;
        std::vector<int> GZ_var;
        std::vector<vector_d> pr_base;
        double prior_lp_x_scale;
        double prior_lp_xr_scale;
        double prior_beta_scale;
        vector_d alpha;
        row_vector_d gz_avg;
public:
    model_simple_additive(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_simple_additive(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_simple_additive_namespace::model_simple_additive";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "n_x", "int", context__.to_vec());
            n_x = int(0);
            vals_i__ = context__.vals_i("n_x");
            pos__ = 0;
            n_x = vals_i__[pos__++];
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "n_r", "int", context__.to_vec());
            n_r = int(0);
            vals_i__ = context__.vals_i("n_r");
            pos__ = 0;
            n_r = vals_i__[pos__++];
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "n_gz", "int", context__.to_vec());
            n_gz = int(0);
            vals_i__ = context__.vals_i("n_gz");
            pos__ = 0;
            n_gz = vals_i__[pos__++];
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "n_gz_col", "int", context__.to_vec());
            n_gz_col = int(0);
            vals_i__ = context__.vals_i("n_gz_col");
            pos__ = 0;
            n_gz_col = vals_i__[pos__++];
            current_statement_begin__ = 14;
            validate_non_negative_index("X", "N", N);
            context__.validate_dims("data initialization", "X", "int", context__.to_vec(N));
            X = std::vector<int>(N, int(0));
            vals_i__ = context__.vals_i("X");
            pos__ = 0;
            size_t X_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < X_k_0_max__; ++k_0__) {
                X[k_0__] = vals_i__[pos__++];
            }
            size_t X_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < X_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "X[i_0__]", X[i_0__], 1);
                check_less_or_equal(function__, "X[i_0__]", X[i_0__], n_x);
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("GZ", "N", N);
            validate_non_negative_index("GZ", "n_gz_col", n_gz_col);
            context__.validate_dims("data initialization", "GZ", "matrix_d", context__.to_vec(N,n_gz_col));
            GZ = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(N, n_gz_col);
            vals_r__ = context__.vals_r("GZ");
            pos__ = 0;
            size_t GZ_j_2_max__ = n_gz_col;
            size_t GZ_j_1_max__ = N;
            for (size_t j_2__ = 0; j_2__ < GZ_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < GZ_j_1_max__; ++j_1__) {
                    GZ(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 16;
            context__.validate_dims("data initialization", "n_nonzero", "int", context__.to_vec());
            n_nonzero = int(0);
            vals_i__ = context__.vals_i("n_nonzero");
            pos__ = 0;
            n_nonzero = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_nonzero", n_nonzero, 1);
            current_statement_begin__ = 17;
            validate_non_negative_index("GZ_var", "n_gz_col", n_gz_col);
            context__.validate_dims("data initialization", "GZ_var", "int", context__.to_vec(n_gz_col));
            GZ_var = std::vector<int>(n_gz_col, int(0));
            vals_i__ = context__.vals_i("GZ_var");
            pos__ = 0;
            size_t GZ_var_k_0_max__ = n_gz_col;
            for (size_t k_0__ = 0; k_0__ < GZ_var_k_0_max__; ++k_0__) {
                GZ_var[k_0__] = vals_i__[pos__++];
            }
            size_t GZ_var_i_0_max__ = n_gz_col;
            for (size_t i_0__ = 0; i_0__ < GZ_var_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "GZ_var[i_0__]", GZ_var[i_0__], 1);
                check_less_or_equal(function__, "GZ_var[i_0__]", GZ_var[i_0__], n_gz);
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("pr_base", "n_r", n_r);
            validate_non_negative_index("pr_base", "N", N);
            context__.validate_dims("data initialization", "pr_base", "vector_d", context__.to_vec(N,n_r));
            pr_base = std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(N, Eigen::Matrix<double, Eigen::Dynamic, 1>(n_r));
            vals_r__ = context__.vals_r("pr_base");
            pos__ = 0;
            size_t pr_base_j_1_max__ = n_r;
            size_t pr_base_k_0_max__ = N;
            for (size_t j_1__ = 0; j_1__ < pr_base_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < pr_base_k_0_max__; ++k_0__) {
                    pr_base[k_0__](j_1__) = vals_r__[pos__++];
                }
            }
            size_t pr_base_i_0_max__ = N;
            for (size_t i_0__ = 0; i_0__ < pr_base_i_0_max__; ++i_0__) {
                stan::math::check_simplex(function__, "pr_base[i_0__]", pr_base[i_0__]);
            }
            current_statement_begin__ = 21;
            context__.validate_dims("data initialization", "prior_lp_x_scale", "double", context__.to_vec());
            prior_lp_x_scale = double(0);
            vals_r__ = context__.vals_r("prior_lp_x_scale");
            pos__ = 0;
            prior_lp_x_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "prior_lp_x_scale", prior_lp_x_scale, 0);
            current_statement_begin__ = 22;
            context__.validate_dims("data initialization", "prior_lp_xr_scale", "double", context__.to_vec());
            prior_lp_xr_scale = double(0);
            vals_r__ = context__.vals_r("prior_lp_xr_scale");
            pos__ = 0;
            prior_lp_xr_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "prior_lp_xr_scale", prior_lp_xr_scale, 0);
            current_statement_begin__ = 23;
            context__.validate_dims("data initialization", "prior_beta_scale", "double", context__.to_vec());
            prior_beta_scale = double(0);
            vals_r__ = context__.vals_r("prior_beta_scale");
            pos__ = 0;
            prior_beta_scale = vals_r__[pos__++];
            check_greater_or_equal(function__, "prior_beta_scale", prior_beta_scale, 0);
            // initialize transformed data variables
            current_statement_begin__ = 27;
            validate_non_negative_index("alpha", "n_x", n_x);
            alpha = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_x);
            stan::math::fill(alpha, DUMMY_VAR__);
            stan::math::assign(alpha,rep_vector(prior_lp_x_scale, n_x));
            current_statement_begin__ = 28;
            validate_non_negative_index("gz_avg", "n_gz_col", n_gz_col);
            gz_avg = Eigen::Matrix<double, 1, Eigen::Dynamic>(n_gz_col);
            stan::math::fill(gz_avg, DUMMY_VAR__);
            stan::math::assign(gz_avg,multiply(rep_row_vector((1.0 / N), N), GZ));
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 38;
            validate_non_negative_index("lp_x_raw", "n_x", n_x);
            num_params_r__ += (n_x - 1);
            current_statement_begin__ = 39;
            validate_non_negative_index("lp_xr_raw", "(n_x - 1)", (n_x - 1));
            validate_non_negative_index("lp_xr_raw", "n_r", n_r);
            num_params_r__ += ((n_x - 1) * n_r);
            current_statement_begin__ = 40;
            validate_non_negative_index("beta_raw", "n_x", n_x);
            validate_non_negative_index("beta_raw", "n_gz_col", n_gz_col);
            validate_non_negative_index("beta_raw", "n_r", n_r);
            num_params_r__ += ((n_x * n_gz_col) * n_r);
            current_statement_begin__ = 41;
            validate_non_negative_index("beta_scale", "n_gz", n_gz);
            num_params_r__ += n_gz;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_simple_additive() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 38;
        if (!(context__.contains_r("lp_x_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lp_x_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lp_x_raw");
        pos__ = 0U;
        validate_non_negative_index("lp_x_raw", "n_x", n_x);
        context__.validate_dims("parameter initialization", "lp_x_raw", "vector_d", context__.to_vec(n_x));
        Eigen::Matrix<double, Eigen::Dynamic, 1> lp_x_raw(n_x);
        size_t lp_x_raw_j_1_max__ = n_x;
        for (size_t j_1__ = 0; j_1__ < lp_x_raw_j_1_max__; ++j_1__) {
            lp_x_raw(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.simplex_unconstrain(lp_x_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lp_x_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 39;
        if (!(context__.contains_r("lp_xr_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable lp_xr_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("lp_xr_raw");
        pos__ = 0U;
        validate_non_negative_index("lp_xr_raw", "(n_x - 1)", (n_x - 1));
        validate_non_negative_index("lp_xr_raw", "n_r", n_r);
        context__.validate_dims("parameter initialization", "lp_xr_raw", "vector_d", context__.to_vec(n_r,(n_x - 1)));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > lp_xr_raw(n_r, Eigen::Matrix<double, Eigen::Dynamic, 1>((n_x - 1)));
        size_t lp_xr_raw_j_1_max__ = (n_x - 1);
        size_t lp_xr_raw_k_0_max__ = n_r;
        for (size_t j_1__ = 0; j_1__ < lp_xr_raw_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lp_xr_raw_k_0_max__; ++k_0__) {
                lp_xr_raw[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t lp_xr_raw_i_0_max__ = n_r;
        for (size_t i_0__ = 0; i_0__ < lp_xr_raw_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(lp_xr_raw[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable lp_xr_raw: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 40;
        if (!(context__.contains_r("beta_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_raw");
        pos__ = 0U;
        validate_non_negative_index("beta_raw", "n_x", n_x);
        validate_non_negative_index("beta_raw", "n_gz_col", n_gz_col);
        validate_non_negative_index("beta_raw", "n_r", n_r);
        context__.validate_dims("parameter initialization", "beta_raw", "matrix_d", context__.to_vec(n_r,n_x,n_gz_col));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > beta_raw(n_r, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n_x, n_gz_col));
        size_t beta_raw_j_2_max__ = n_gz_col;
        size_t beta_raw_j_1_max__ = n_x;
        size_t beta_raw_k_0_max__ = n_r;
        for (size_t j_2__ = 0; j_2__ < beta_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_raw_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_raw_k_0_max__; ++k_0__) {
                    beta_raw[k_0__](j_1__, j_2__) = vals_r__[pos__++];
                }
            }
        }
        size_t beta_raw_i_0_max__ = n_r;
        for (size_t i_0__ = 0; i_0__ < beta_raw_i_0_max__; ++i_0__) {
            try {
                writer__.matrix_unconstrain(beta_raw[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_raw: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 41;
        if (!(context__.contains_r("beta_scale")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_scale missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_scale");
        pos__ = 0U;
        validate_non_negative_index("beta_scale", "n_gz", n_gz);
        context__.validate_dims("parameter initialization", "beta_scale", "row_vector_d", context__.to_vec(n_gz));
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta_scale(n_gz);
        size_t beta_scale_j_1_max__ = n_gz;
        for (size_t j_1__ = 0; j_1__ < beta_scale_j_1_max__; ++j_1__) {
            beta_scale(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.row_vector_lb_unconstrain(0, beta_scale);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_scale: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 38;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lp_x_raw;
            (void) lp_x_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                lp_x_raw = in__.simplex_constrain(n_x, lp__);
            else
                lp_x_raw = in__.simplex_constrain(n_x);
            current_statement_begin__ = 39;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > lp_xr_raw;
            size_t lp_xr_raw_d_0_max__ = n_r;
            lp_xr_raw.reserve(lp_xr_raw_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < lp_xr_raw_d_0_max__; ++d_0__) {
                if (jacobian__)
                    lp_xr_raw.push_back(in__.vector_constrain((n_x - 1), lp__));
                else
                    lp_xr_raw.push_back(in__.vector_constrain((n_x - 1)));
            }
            current_statement_begin__ = 40;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > beta_raw;
            size_t beta_raw_d_0_max__ = n_r;
            beta_raw.reserve(beta_raw_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < beta_raw_d_0_max__; ++d_0__) {
                if (jacobian__)
                    beta_raw.push_back(in__.matrix_constrain(n_x, n_gz_col, lp__));
                else
                    beta_raw.push_back(in__.matrix_constrain(n_x, n_gz_col));
            }
            current_statement_begin__ = 41;
            Eigen::Matrix<local_scalar_t__, 1, Eigen::Dynamic> beta_scale;
            (void) beta_scale;  // dummy to suppress unused var warning
            if (jacobian__)
                beta_scale = in__.row_vector_lb_constrain(0, n_gz, lp__);
            else
                beta_scale = in__.row_vector_lb_constrain(0, n_gz);
            // transformed parameters
            current_statement_begin__ = 45;
            validate_non_negative_index("beta", "n_x", n_x);
            validate_non_negative_index("beta", "n_gz_col", n_gz_col);
            validate_non_negative_index("beta", "n_r", n_r);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> > beta(n_r, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(n_x, n_gz_col));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 47;
            for (int r = 1; r <= n_r; ++r) {
                current_statement_begin__ = 48;
                for (int x = 1; x <= n_x; ++x) {
                    current_statement_begin__ = 49;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(x), stan::model::nil_index_list())), 
                                elt_multiply(stan::model::rvalue(beta_scale, stan::model::cons_list(stan::model::index_multi(GZ_var), stan::model::nil_index_list()), "beta_scale"), get_base1(get_base1(beta_raw, r, "beta_raw", 1), x, "beta_raw", 2)), 
                                "assigning variable beta");
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 45;
            size_t beta_k_0_max__ = n_r;
            size_t beta_j_1_max__ = n_x;
            size_t beta_j_2_max__ = n_gz_col;
            for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                        if (stan::math::is_uninitialized(beta[k_0__](j_1__, j_2__))) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: beta" << "[" << k_0__ << "]" << "(" << j_1__ << ", " << j_2__ << ")";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            // model body
            {
            current_statement_begin__ = 55;
            validate_non_negative_index("linpred", "n_x", n_x);
            validate_non_negative_index("linpred", "N", N);
            validate_non_negative_index("linpred", "n_r", n_r);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>  > linpred(n_r, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic>(n_x, N));
            stan::math::initialize(linpred, DUMMY_VAR__);
            stan::math::fill(linpred, DUMMY_VAR__);
            current_statement_begin__ = 56;
            validate_non_negative_index("lp_xr", "n_x", n_x);
            validate_non_negative_index("lp_xr", "n_r", n_r);
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>  > lp_xr(n_r, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(n_x));
            stan::math::initialize(lp_xr, DUMMY_VAR__);
            stan::math::fill(lp_xr, DUMMY_VAR__);
            current_statement_begin__ = 57;
            for (int r = 1; r <= n_r; ++r) {
                current_statement_begin__ = 58;
                stan::model::assign(linpred, 
                            stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list()), 
                            multiply(get_base1(beta, r, "beta", 1), transpose(GZ)), 
                            "assigning variable linpred");
                current_statement_begin__ = 61;
                stan::model::assign(lp_xr, 
                            stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list()), 
                            add(stan::math::log(lp_x_raw), append_row(0, get_base1(lp_xr_raw, r, "lp_xr_raw", 1))), 
                            "assigning variable lp_xr");
            }
            current_statement_begin__ = 64;
            for (int i = 1; i <= N; ++i) {
                {
                current_statement_begin__ = 65;
                validate_non_negative_index("p_xr_i", "n_x", n_x);
                validate_non_negative_index("p_xr_i", "n_r", n_r);
                Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> p_xr_i(n_x, n_r);
                stan::math::initialize(p_xr_i, DUMMY_VAR__);
                stan::math::fill(p_xr_i, DUMMY_VAR__);
                current_statement_begin__ = 66;
                for (int r = 1; r <= n_r; ++r) {
                    current_statement_begin__ = 67;
                    stan::model::assign(p_xr_i, 
                                stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list())), 
                                softmax(add(get_base1(lp_xr, r, "lp_xr", 1), stan::model::rvalue(linpred, stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()))), "linpred"))), 
                                "assigning variable p_xr_i");
                }
                current_statement_begin__ = 69;
                lp_accum__.add(categorical_log<propto__>(get_base1(X, i, "X", 1), multiply(p_xr_i, get_base1(pr_base, i, "pr_base", 1))));
                }
            }
            current_statement_begin__ = 73;
            lp_accum__.add(dirichlet_log<propto__>(lp_x_raw, alpha));
            current_statement_begin__ = 74;
            lp_accum__.add(student_t_log<propto__>(beta_scale, 4, 0.0, prior_beta_scale));
            current_statement_begin__ = 75;
            for (int r = 1; r <= n_r; ++r) {
                current_statement_begin__ = 76;
                lp_accum__.add(student_t_log<propto__>(get_base1(lp_xr_raw, r, "lp_xr_raw", 1), 4, 0.0, prior_lp_xr_scale));
                current_statement_begin__ = 77;
                for (int x = 1; x <= n_x; ++x) {
                    current_statement_begin__ = 78;
                    lp_accum__.add(std_normal_log<propto__>(get_base1(get_base1(beta_raw, r, "beta_raw", 1), x, "beta_raw", 2)));
                }
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("lp_x_raw");
        names__.push_back("lp_xr_raw");
        names__.push_back("beta_raw");
        names__.push_back("beta_scale");
        names__.push_back("beta");
        names__.push_back("p_xr");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(n_x);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_r);
        dims__.push_back((n_x - 1));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_r);
        dims__.push_back(n_x);
        dims__.push_back(n_gz_col);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_gz);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_r);
        dims__.push_back(n_x);
        dims__.push_back(n_gz_col);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_x);
        dims__.push_back(n_r);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_simple_additive_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> lp_x_raw = in__.simplex_constrain(n_x);
        size_t lp_x_raw_j_1_max__ = n_x;
        for (size_t j_1__ = 0; j_1__ < lp_x_raw_j_1_max__; ++j_1__) {
            vars__.push_back(lp_x_raw(j_1__));
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > lp_xr_raw;
        size_t lp_xr_raw_d_0_max__ = n_r;
        lp_xr_raw.reserve(lp_xr_raw_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < lp_xr_raw_d_0_max__; ++d_0__) {
            lp_xr_raw.push_back(in__.vector_constrain((n_x - 1)));
        }
        size_t lp_xr_raw_j_1_max__ = (n_x - 1);
        size_t lp_xr_raw_k_0_max__ = n_r;
        for (size_t j_1__ = 0; j_1__ < lp_xr_raw_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lp_xr_raw_k_0_max__; ++k_0__) {
                vars__.push_back(lp_xr_raw[k_0__](j_1__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > beta_raw;
        size_t beta_raw_d_0_max__ = n_r;
        beta_raw.reserve(beta_raw_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < beta_raw_d_0_max__; ++d_0__) {
            beta_raw.push_back(in__.matrix_constrain(n_x, n_gz_col));
        }
        size_t beta_raw_j_2_max__ = n_gz_col;
        size_t beta_raw_j_1_max__ = n_x;
        size_t beta_raw_k_0_max__ = n_r;
        for (size_t j_2__ = 0; j_2__ < beta_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_raw_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_raw_k_0_max__; ++k_0__) {
                    vars__.push_back(beta_raw[k_0__](j_1__, j_2__));
                }
            }
        }
        Eigen::Matrix<double, 1, Eigen::Dynamic> beta_scale = in__.row_vector_lb_constrain(0, n_gz);
        size_t beta_scale_j_1_max__ = n_gz;
        for (size_t j_1__ = 0; j_1__ < beta_scale_j_1_max__; ++j_1__) {
            vars__.push_back(beta_scale(j_1__));
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 45;
            validate_non_negative_index("beta", "n_x", n_x);
            validate_non_negative_index("beta", "n_gz_col", n_gz_col);
            validate_non_negative_index("beta", "n_r", n_r);
            std::vector<Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> > beta(n_r, Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n_x, n_gz_col));
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 47;
            for (int r = 1; r <= n_r; ++r) {
                current_statement_begin__ = 48;
                for (int x = 1; x <= n_x; ++x) {
                    current_statement_begin__ = 49;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(r), stan::model::cons_list(stan::model::index_uni(x), stan::model::nil_index_list())), 
                                elt_multiply(stan::model::rvalue(beta_scale, stan::model::cons_list(stan::model::index_multi(GZ_var), stan::model::nil_index_list()), "beta_scale"), get_base1(get_base1(beta_raw, r, "beta_raw", 1), x, "beta_raw", 2)), 
                                "assigning variable beta");
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t beta_j_2_max__ = n_gz_col;
                size_t beta_j_1_max__ = n_x;
                size_t beta_k_0_max__ = n_r;
                for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                        for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                            vars__.push_back(beta[k_0__](j_1__, j_2__));
                        }
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 84;
            validate_non_negative_index("p_xr", "n_x", n_x);
            validate_non_negative_index("p_xr", "n_r", n_r);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> p_xr(n_x, n_r);
            stan::math::initialize(p_xr, DUMMY_VAR__);
            stan::math::fill(p_xr, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 85;
            for (int r = 1; r <= n_r; ++r) {
                current_statement_begin__ = 86;
                stan::model::assign(p_xr, 
                            stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(r), stan::model::nil_index_list())), 
                            softmax(add(add(stan::math::log(lp_x_raw), append_row(0, get_base1(lp_xr_raw, r, "lp_xr_raw", 1))), multiply(get_base1(beta, r, "beta", 1), transpose(gz_avg)))), 
                            "assigning variable p_xr");
            }
            // validate, write generated quantities
            current_statement_begin__ = 84;
            size_t p_xr_j_2_max__ = n_r;
            size_t p_xr_j_1_max__ = n_x;
            for (size_t j_2__ = 0; j_2__ < p_xr_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < p_xr_j_1_max__; ++j_1__) {
                    vars__.push_back(p_xr(j_1__, j_2__));
                }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_simple_additive";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t lp_x_raw_j_1_max__ = n_x;
        for (size_t j_1__ = 0; j_1__ < lp_x_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lp_x_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lp_xr_raw_j_1_max__ = (n_x - 1);
        size_t lp_xr_raw_k_0_max__ = n_r;
        for (size_t j_1__ = 0; j_1__ < lp_xr_raw_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lp_xr_raw_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lp_xr_raw" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_raw_j_2_max__ = n_gz_col;
        size_t beta_raw_j_1_max__ = n_x;
        size_t beta_raw_k_0_max__ = n_r;
        for (size_t j_2__ = 0; j_2__ < beta_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_raw_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_raw_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "beta_raw" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t beta_scale_j_1_max__ = n_gz;
        for (size_t j_1__ = 0; j_1__ < beta_scale_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_scale" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_j_2_max__ = n_gz_col;
            size_t beta_j_1_max__ = n_x;
            size_t beta_k_0_max__ = n_r;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t p_xr_j_2_max__ = n_r;
        size_t p_xr_j_1_max__ = n_x;
        for (size_t j_2__ = 0; j_2__ < p_xr_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_xr_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p_xr" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t lp_x_raw_j_1_max__ = (n_x - 1);
        for (size_t j_1__ = 0; j_1__ < lp_x_raw_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lp_x_raw" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lp_xr_raw_j_1_max__ = (n_x - 1);
        size_t lp_xr_raw_k_0_max__ = n_r;
        for (size_t j_1__ = 0; j_1__ < lp_xr_raw_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < lp_xr_raw_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lp_xr_raw" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_raw_j_2_max__ = n_gz_col;
        size_t beta_raw_j_1_max__ = n_x;
        size_t beta_raw_k_0_max__ = n_r;
        for (size_t j_2__ = 0; j_2__ < beta_raw_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < beta_raw_j_1_max__; ++j_1__) {
                for (size_t k_0__ = 0; k_0__ < beta_raw_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "beta_raw" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t beta_scale_j_1_max__ = n_gz;
        for (size_t j_1__ = 0; j_1__ < beta_scale_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta_scale" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_j_2_max__ = n_gz_col;
            size_t beta_j_1_max__ = n_x;
            size_t beta_k_0_max__ = n_r;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    for (size_t k_0__ = 0; k_0__ < beta_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "beta" << '.' << k_0__ + 1 << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t p_xr_j_2_max__ = n_r;
        size_t p_xr_j_1_max__ = n_x;
        for (size_t j_2__ = 0; j_2__ < p_xr_j_2_max__; ++j_2__) {
            for (size_t j_1__ = 0; j_1__ < p_xr_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "p_xr" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
    }
}; // model
}  // namespace
typedef model_simple_additive_namespace::model_simple_additive stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
