# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gibbs_race <- function(iter, warmup, X, S, GZ, M_sr, N_gzr, alpha_sr, beta_gzr, verbosity) {
    .Call(`_raceproxy_gibbs_race`, iter, warmup, X, S, GZ, M_sr, N_gzr, alpha_sr, beta_gzr, verbosity)
}

