# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_bayes_bisg <- function(S, GX, p_sr, p_gxr, p_r) {
    .Call(`_birdie_calc_bayes_bisg`, S, GX, p_sr, p_gxr, p_r)
}

calc_bayes <- function(Y, X, lik, prior, n_x, n_y) {
    .Call(`_birdie_calc_bayes`, Y, X, lik, prior, n_x, n_y)
}

dirichlet_map <- function(Y, X, p_rxs, prior_yr, n_x) {
    .Call(`_birdie_dirichlet_map`, Y, X, p_rxs, prior_yr, n_x)
}

em_dirichlet <- function(curr, Y, X, p_rxs, prior_yr, n_x, sum_only = FALSE) {
    .Call(`_birdie_em_dirichlet`, curr, Y, X, p_rxs, prior_yr, n_x, sum_only)
}

em_dirichlet_wt <- function(curr, Y, X, wt, p_rxs, prior_yr, n_x) {
    .Call(`_birdie_em_dirichlet_wt`, curr, Y, X, wt, p_rxs, prior_yr, n_x)
}

gibbs_dir_step <- function(Y, X, wt, p_ryxs, prior_yr, n_x) {
    .Call(`_birdie_gibbs_dir_step`, Y, X, wt, p_ryxs, prior_yr, n_x)
}

resid_mult <- function(m_coef, idxs, r_probs, k, n_k) {
    .Call(`_birdie_resid_mult`, m_coef, idxs, r_probs, k, n_k)
}

safeexpoffset <- function(Y) {
    .Call(`_birdie_safeexpoffset`, Y)
}

gibbs_me <- function(iter, warmup, S, GZ, M_sr, N_gzr, alpha_gzr, beta_sr, cores = 0L, verbosity = 3L) {
    .Call(`_birdie_gibbs_me`, iter, warmup, S, GZ, M_sr, N_gzr, alpha_gzr, beta_sr, cores, verbosity)
}

mat_rcatp <- function(probs) {
    .Call(`_birdie_mat_rcatp`, probs)
}

rdirichlet <- function(alpha, m) {
    .Call(`_birdie_rdirichlet`, alpha, m)
}

